version: '3.7'
services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - test

  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: always
    depends_on:
      - nginx-proxy  
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - '8080:80'
    networks:
      - test

    environment:
      - VIRTUAL_HOST=gitlab.local

networks:
  test:
    name: test-network